#+TITLE: gitto
#+STARTUP: showall

* NAME

  gitto - A silly utility to track the status of some git
  repositories.

* SYNOPSIS

  =gitto [command [subcommand] [args...]]=

* DESCRIPTION

  For lack of a better title.

  My simple utility to keep track of all the git repositories I have on
  my computer(s). Also an experiment in writing scheme.

  Written for [[http://gnu.org/software/guile][GNU Guile]] 2.0.9 or newer

* USAGE

  Usage is, hopefully, simple, first you have to register some repos:

  : $ gitto add ~/projects/project1
  : $ gitto add ~/projects/project2
  : $ gitto add ~/projects/project3

  Then you can call ~gitto~ without any argument to see a list of your
  repos and their statuses:

  : $ gitto
  : project1: Worktree is dirty
  :   master:      0 to push and 0 to pull. Last update: 4 weeks ago
  :
  : project2: Worktree is clean
  :   master:      5 to push and 2 to pull. Last update: 2 days ago
  :
  : project3: Worktree is clean
  :   master:      0 to push and 1 to pull. Last update: 1 hour ago

  If you're done with one of your projects and no longer wish to track
  their status you can unregister them:

  : $ gitto remove ~/projects/project1

  If you require further assistance:

  : $ gitto help

** run-gitto

   It is not strictly necessary to install gitto, I have added a
   utility to run it straight from the project directory, although
   mostly for testing purposes.

   Using ~run-gitto~ works exactly the same as using ~gitto~ when it is
   installed.
